version: '3.7'

services:
  nginx:                     #Declaration to define for nginx.
    build: ./nginx           #Dockerfile path
    image: front:0.0.2       #Specify the image name
    container_name: "front"  #Specify the container name
    ports:                   #Specify the contents of the port disclosure.
      - "8080:80"            #If it is 80 on the container side, it will be 8080 on the host side.
    depends_on:
      - app
    volumes:                 #Add the host folder to the container. Host side:Container side
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf  #Copy config file
      - ./nginx/src:/usr/share/nginx/html         #Copy

  app:
    build:
      context: .
      dockerfile: docker/deploy/Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8000:8000

  mysql:
    platform: linux/amd64
    image: mysql:5.7
    container_name: godockerDB
    restart: unless-stopped
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: todolist
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql"

